### ISSUE TITLE
E_USER_WARNING: Invalid parameter for message "logentry-tilesheet-deletesheet": a:1:{i:0;s:3:&quot;TDM&quot;;}

### ISSUE THREAD

**Issue by Alexia** [FTB-Gamepedia/Tilesheets#23]
This came out of New Relic error reporting.  I can not find exactly what caused it other than the user being on Special:RecentChanges.

in trigger_error called at includes/Message.php (1078)
in Message::extractParam called at includes/Message.php (1037)
…sage::replaceParameters called at includes/Message.php (804)
in Message::toString called at includes/Message.php (897)
…e::escaped called at includes/logging/LogFormatter.php (407)
…tActionText called at includes/changes/ChangesList.php (442)
…LogEntry called at includes/changes/OldChangesList.php (115)
…angeLine called at includes/changes/OldChangesList.php (51)
…e called at includes/specials/SpecialRecentchanges.php (356)
…led at includes/specialpage/ChangesListSpecialPage.php (348)
…led at includes/specialpage/ChangesListSpecialPage.php (77)
…e called at includes/specials/SpecialRecentchanges.php (64)
…execute called at includes/specialpage/SpecialPage.php (384)
… called at includes/specialpage/SpecialPageFactory.php (553)
…eFactory::executePath called at includes/MediaWiki.php (281)
…aWiki::performRequest called at includes/MediaWiki.php (714)
in MediaWiki::main called at includes/MediaWiki.php (508)
in MediaWiki::run called at index.php (41)

**Comment by elifoster** [comment]
IIRC it's caused by the sheet deletion logs, with the mod abbreviation being [INVALID].

**Comment by elifoster** [comment]
@Alexia is this still happening?
