### ISSUE TITLE
Licensing and Repository Ownership [Tilesheets]

### ISSUE THREAD

**Issue by Alexia** [FTB-Gamepedia/Tilesheets#44]
There are two legal issues need to be taken care of by the end of next week.

1.) Licensing
There was discussion on the #gamepedia IRC channel previously about this.  I forget what the final open source license was decided on and if it was for OreDict or Tilesheets.

The company(Curse Inc.) is requesting to be able to use Tilesheets under the MIT license.  However, if not MIT then GPLv2 would be acceptable.

Preferably the license would be included in the repository in the root folder titled similar to "LICENSE" in all capital letters.

* [x] @elifoster
* [x] @noahm
* [x] @Alexia 
* [x] @Majr- 
* [x] @Telshin 
* [x] @xbony2 
* [x] @Developaws 
* [x] @applehat 
* [x] @retep998 

2.) Repository Ownership
Even though Tilesheets is used primarily on a Gamepedia wiki the primary maintainers of the Tilesheets project are not Curse employees or contractors.  As such legal has informed us that it would be best that the repository ownership be officially transferred to either the personal Github account of a primary maintainer or a an organization account controlled by the primary maintainers.  I will facilitate transferring the repository to the location decided.

**Comment by xbony2** [comment]
If you are going to move it, move it to the [FTB-Gamepedia group](https://github.com/FTB-Gamepedia). It's where we host our bots/libraries/other software.

**Comment by elifoster** [comment]
I'm cool with the MIT license. The discussion was about HeaderCount, which did get relicensed.

**Comment by retep998** [comment]
I am okay with MIT.

**Comment by Alexia** [comment]
This appears to be the representative group of non-Curse employee/contractor contributors.  Are we good to move it over to the FTB-Gamepedia group?

**Comment by Telshin** [comment]
I'm good with both MIT and the move.

**Comment by elifoster** [comment]
I am also alright with it being moved to FTB-Gamepedia.

**Comment by Alexia** [comment]
@elifoster, I gave the FTB team here access to transfer the repository.  I can not complete it myself since I do not have access to FTB-Gamepedia.

**Comment by noahm** [comment]
MIT is my favorite license!

**Comment by applehat** [comment]
I'm good with this.

**Comment by xbony2** [comment]
You have my permission.

**Comment by Developaws** [comment]
:+1:

**Comment by Majr-** [comment]
Fine by me.
