### ISSUE TITLE
ViewTile special page

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/Tilesheets#62]
It's not super-useful, but having a special page for looking at a particular tile could be useful. The unofficial wiki and the Minecraft wiki use single-image tiles so they can be linked to which is useful (for example, linking to https://ftbwiki.org/File:Grid_Dragon_Heart.png was used to help create the /r/ftb part of /r/place).

**Comment by elifoster** [comment]
I think this would be better to put into the TileManager. What do you think?

**Comment by xbony2** [comment]
I was thinking that too, but that would be awkward for those just intending to view a particular tile when editing tools are not relevant to them. Ideally it would be more like a tool for non-wiki use.

(Not against having an image in the TileManager though)
