### ISSUE TITLE
Item List index value incrementing by 3

### ISSUE THREAD

**Issue by tzwolsman14** [FTB-Gamepedia/Tilesheets#75]
For some reason all new items that get added to the item list have an index that is incrementing by 3 rather than 1.

For example:
https://ftb.gamepedia.com/index.php?title=Special:TileList&page=17&regex=&mod=&langs=&invertlang=0&limit=5000

  |   |  | # | Item name | Mod name | X position | Y position | Registered sizes
-- | -- | -- | -- | -- | -- | -- | --|--
Edit | Translate | View | **272089** | Lazurite Plate | TR | 13 | 15 | 16px,32px
Edit | Translate | View | **272092** | Lead Dust | TR | 14 | 15 | 16px,32px
Edit | Translate | View | **272095** | Magic Energy Absorber | TR | 15 | 15 | 16px,32px

**Comment by elifoster** [comment]
This is a Gamepedia thing relating to the server setup they have come up with.
