### ISSUE TITLE
Don't fallback when a mod is specified for a tilesheet that doesn't exist yet

### ISSUE THREAD

**Issue by retep998** [FTB-Gamepedia/Tilesheets#81]
For example `{{Gc|mod=NUCC|Basic Solar Panel}}`. There is no `NUCC` tilesheet, although the abbreviation is registered in `Module:Mods/list`. It will fall back to the tile from the `GAL` tilesheet despite the user explicitly asking for `NUCC`.

Change this so that if the `mod` is specified, it will never fallback, even if the tilesheet doesn't exist.

**Comment by xbony2** [comment]
Come to think about it, do we really need fallbacks in the first place?

**Comment by elifoster** [comment]
It's designed for new users who might not understand the whole abbreviation stuff, I think. I don't really care either way, honestly.

**Comment by retep998** [comment]
I am in favor of removing fallback once all pages that use fallback have been fixed to explicitly specify the mod.

**Comment by xbony2** [comment]
Pretty sure it's just an old relic from the times of G. Are pages that use fallback categorized?

**Comment by elifoster** [comment]
Kind of. It's not that they are categorized for using fallbacks, but they are categorized when no mod is specified and there's a specific category for when no mod is specified *and* it uses a fallback.

**Comment by retep998** [comment]
This is actually a lua issue. `Module:Grid` and `Module:Mods` will default to specifying the mod as nothing if it cannot be found in `Module:Mods`, thus resulting in invoking this extension with no mod specified.
