### ISSUE TITLE
E_WARNING: current() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by Alexia** [FTB-Gamepedia/Tilesheets#83]
From the just deployed update.

E_WARNING: current() expects parameter 1 to be array, null given

in current called at extensions/Tilesheets/Tilesheets.body.php (95)
…::output called at extensions/Tilesheets/Tilesheets.hooks.php (79)
…heetsHooks::RenderParser called at includes/parser/Parser.php (3408)
…alled at extensions/Scribunto/engines/LuaCommon/LuaCommon.php (725)
…extensions/Scribunto/engines/LuaStandalone/LuaStandaloneEngine.php (452)
…extensions/Scribunto/engines/LuaStandalone/LuaStandaloneEngine.php (429)
…extensions/Scribunto/engines/LuaStandalone/LuaStandaloneEngine.php (477)
…extensions/Scribunto/engines/LuaStandalone/LuaStandaloneEngine.php (353)
…alled at extensions/Scribunto/engines/LuaCommon/LuaCommon.php (266)
…alled at extensions/Scribunto/engines/LuaCommon/LuaCommon.php (914)
…odule::invoke called at extensions/Scribunto/common/Hooks.php (130)
…ribuntoHooks::invokeHook called at includes/parser/Parser.php (3408)
…rser::callParserFunction called at includes/parser/Parser.php (3128)
…ceSubstitution called at includes/parser/Preprocessor_DOM.php (1199)
in PPFrame_DOM::expand called at includes/parser/Parser.php (3282)
…ceSubstitution called at includes/parser/Preprocessor_DOM.php (1199)
…me_DOM::expand called at includes/parser/Preprocessor_DOM.php (1721)
…tNamedArgument called at includes/parser/Preprocessor_DOM.php (1733)
…teFrame_DOM::getArgument called at includes/parser/Parser.php (3794)
…rgSubstitution called at includes/parser/Preprocessor_DOM.php (1218)

**Comment by Alexia** [comment]
I put this patch on Hydra and it should get deployed this week.

**Comment by elifoster** [comment]
There's a few other problems that have been pointed out on IRC/Discord that I'll be working through so I'd say you can expect another deploy request at some point in the near future :100:
