### ISSUE TITLE
Update needed for 1.33 - mediawiki.api usage

### ISSUE THREAD

**Issue by chaud** [FTB-Gamepedia/Tilesheets#92]
> The following 'mediawiki.api' plugin modules were merged into mediawiki.api and deprecated: mediawiki.api.category, mediawiki.api.edit, mediawiki.api.login, mediawiki.api.options, mediawiki.api.parse, mediawiki.api.upload, mediawiki.api.user, mediawiki.api.watch, mediawiki.api.messages, and mediawiki.api.rollback.

https://github.com/FTB-Gamepedia/Tilesheets/blob/8542daa142beffac6fd10ce004fdfa82c320a0e5/js/tilesheets.viewtile.js#L26

**Comment by elifoster** [comment]
Based on SemanticMediaWiki/SemanticMediaWiki#3626, I believe all that will be needed is removing `'mediawiki.api.messages'` from that list, however I'll have to look into it a bit more in the coming week/two.
